### ISSUE TITLE
一直404 error

### ISSUE THREAD

**Issue by Midcc** [halloffamezwx/zshop#2]
配置文件：
var config = {
    dialect: 'mysql',
    database: 'zshop',
    username: 'root',
    password: 'root',
    host: '192.168.1.215',
    port: 3306,
    rootpath: 'zshop'
};

module.exports = config;

请求返回http://localhost:3000/static/html/404.html

请问是什么问题？

**Comment by halloffamezwx** [comment]
rootpath: '/zshop'  这个加多一个斜杠看看

**Comment by halloffamezwx** [comment]
@Midcc rootpath: '/zshop' 这个加多一个斜杠看看

**Comment by machiming** [comment]
一直404 error
